server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eddaniel01/config-repo.git
          default-label: main
          search-paths: .
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/