server:
  port: 8082
spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librosdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
