server:
  port: 8081

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
        - id: carrito-service
          uri: lb://carrito-service
          predicates:
            - Path=/api/cart/**
        # Agrega aquí los otros servicios conforme los crees

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
