version: '3.8'
services:
  app1:
    image: eddaniel01/mockup-api-server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-testdb}
      DB_USER: ${DB_USER:-testuser}
      DB_PASSWORD: ${DB_PASSWORD:-testpass}
    depends_on:
      - db
    networks:
      - app-network

  app2:
    image: eddaniel01/mockup-api-server
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-testdb}
      DB_USER: ${DB_USER:-testuser}
      DB_PASSWORD: ${DB_PASSWORD:-testpass}
    depends_on:
      - db
    networks:
      - app-network

  app3:
    image: eddaniel01/mockup-api-server
    ports:
      - "8082:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-testdb}
      DB_USER: ${DB_USER:-testuser}
      DB_PASSWORD: ${DB_PASSWORD:-testpass}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-testdb}
      MYSQL_USER: ${DB_USER:-testuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-testpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
