spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
